### ISSUE TITLE
怎样将 cnki 导出的数据用 vosviewer 可视化呢？

### ISSUE THREAD

**Issue by et2010** [wshuyi/demo-vosviewer-CNKI-keyword-co-occurence-analysis#1]
感谢分享，不知道这个 repo 是不是用于这个目的，@wshuyi 能不能说明一下用法，谢谢！

**Comment by wshuyi** [comment]
https://www.jianshu.com/p/bdf69db5bfcb
https://www.jianshu.com/p/4dce3396068e

**Comment by et2010** [comment]
谢谢！
